metrics:
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: ${PROMETHEUS_PASSWORD}
            username: ${PROMETHEUS_USERNAME}
          url: ${PROMETHEUS_PUSH_URL}
      scrape_configs:
        - job_name: app
          static_configs:
            - targets: ["${PROMETHEUS_TARGET_URL}"]
  global:
    scrape_interval: 60s
  wal_directory: /tmp/grafana-agent-wal
