metrics:
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: ${PROMETHEUS_PASSWORD}
            username: ${PROMETHEUS_USERNAME}
          url: ${PROMETHEUS_PUSH_URL}
      scrape_configs:
        - job_name: app
          static_configs:
            - targets: ["${PROMETHEUS_TARGET_URL}"]
  global:
    scrape_interval: 60s
  wal_directory: /tmp/grafana-agent-wal

logs:
  configs:
    - name: default
      positions:
        filename: /tmp/position.yaml
      scrape_configs:
        - job_name: app
          pipeline_stages:
            - json:
                expressions:
                  channel: channel
                  level: level_name
                  timestamp: datetime
            - labels:
                channel:
                level:
            - timestamp:
                source: timestamp
                format: RFC3339
          static_configs:
            - targets: ["${LOKI_TARGET_URL}"]
              labels:
                job: app
                __path__: storage/logs/*.log
      clients:
        - url: ${LOKI_PUSH_URL}
          basic_auth:
            username: ${LOKI_USERNAME}
            password: ${LOKI_PASSWORD}
