# For more information: https://laravel.com/docs/sail
version: "3"
services:
  laravel:
    build:
      context: ./docker/sail/8.1
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.1/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    volumes:
      - ".:/var/www/html"
    networks:
      - sail
    depends_on:
      - postgres
  postgres:
    image: "postgres:14-alpine"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    env_file:
      - ./docker/database.env
    volumes:
      - sailpgsql:/var/lib/postgresql/data/
    networks:
      - sail
  influxdb:
    image: "influxdb:2.0-alpine"
    ports:
      - "8086:8086"
    env_file:
      - ./docker/influxdb.env
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - sail
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - sail
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sailpgsql:
  influxdb-data:
  grafana-data:
  redis-data:
