# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - postgres
    postgres:
        image: 'postgres:14-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        env_file:
          - database.env
        volumes:
            - sailpgsql:/var/lib/postgresql/data/
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailpgsql:

