name: Analysis and unit tests

on:
  pull_request:
    branches: [master, staging]
  push:
    branches: [master, staging]

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: secret

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          extensions: redis

      - name: Check Composer configuration
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Lint application
        run: ./vendor/bin/pint --test

      - name: Analyze code
        run: ./vendor/bin/phpstan analyze --ansi --no-interaction --no-progress

      - name: Run unit tests
        run: ./vendor/bin/pest --testsuite=Unit
