name: Analysis and unit tests

on:
  pull_request:
    branches: [master, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: "dom, curl, libxml, mbstring, zip, fileinfo"
          tools: composer:v2, phpunit

      - name: Check Composer configuration
        run: composer validate --strict

      - name: Install pint
        run: composer require laravel/pint --dev

      - name: Lint application
        run: composer lint

      - name: Install larastan
        run: composer require nunomaduro/larastan:^2.0 --dev

      - name: Analyze code
        run: composer analyze

      - name: Run unit tests
        run: phpunit --testsuite=Unit
