name: Analysis and unit tests

on:
  pull_request:
    branches: [master, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: "composer:v2", "pint", "phpstan", "phpunit"

      - name: Check Composer configuration
        run: composer validate --strict

      - name: Lint application
        run: pint

      - name: Analyze code
        run: phpstan

      - name: Run unit tests
        run: phpunit --testsuite=Unit
