name: Analysis and unit tests

on:
  pull_request:
    branches: [master, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: "composer:v2"

      - name: Check Composer configuration
        run: composer validate --strict

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Lint application
        run: composer lint

      - name: Analyze code
        run: composer analyze

      - name: Run unit tests
        run: ./vendor/bin/phpunit --testsuite=Unit
