name: CI

on:
  pull_request:
    branches: [master, staging]

jobs:
  postgresql:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: ani
          POSTGRES_PASSWORD: password
          POSTGRES_DB: anikultura
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Postgres client
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client

      - name: Create testing database
        run: psql -f ./database/init.sql postgresql://ani:password@postgres:5432/postgres

      - name: Build, lint, and test application
        uses: ./.github/actions/build
        env:
          DB_CONNECTION: pgsql
          DB_HOST: postgres
          DB_PORT: 5432

  mysql:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: ani
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: anikultura
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Create testing database
        run: mysql -h mysql -u root -p password --port 3306 < ./database/init.sql

      - name: Build, lint, and test application
        uses: ./.github/actions/build
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
