name: Pull Request Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull Request title rules
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: '(\[ANI-[0-9]+\])(.)*'
